name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Run docker compose
      run: |
        docker compose up -d
        sleep 10
        
    - name: Check container is running
      run: |
        docker ps | grep trackit-api
