name: Docker Image

on:
  push:
    branches: [ "main", "dev", "feat-jwt" ]
  pull_request:
    branches: [ "main" ]

env:
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DEBUG: ${{ secrets.DEBUG }}
  SLOW_REQUEST_THRESHOLD: ${{ secrets.SLOW_REQUEST_THRESHOLD }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ALGORITHM: ${{ secrets.ALGORITHM }}
  ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Build the Docker image
      run: docker build -t trackit-api:latest .
      
    - name: Run docker compose
      run: |
        docker compose up -d --build
        sleep 5
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    - name: Show API logs
      run: |
        docker logs trackit-api --tail 50
    
    - name: Wait for Postgres
      run: |
        timeout 60s bash -c 'until docker exec pg-db pg_isready -U trackit; do sleep 1; done'
        
    - name: Check container is running
      run: |
        docker ps | grep trackit-api
